name: Descarga Automatizada Diario

on:
  schedule:
    - cron: '50 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  descargar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar librer√≠as
        run: pip install -r requirements.txt
        
      - name: Correr script
        run: python scraper.py
        
      - name: Guardar cambios
        run: |
          git config --global user.name "Bot de Datos"
          git config --global user.email "bot@github.com"
          git add data/
          # Verificamos si hay cambios antes de hacer commit para no generar error si no hubo tabla nueva
          if git diff --staged --quiet; then
            print("No hay cambios para guardar.")
          else
            git commit -m "Nuevos datos: $(date +'%Y-%m-%d') [skip ci]"
            git pull --rebase origin main # Evita conflictos si hay commits nuevos
            git push
          fi
