name: Descarga diaria visitas

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  descargar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Instalar Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Subir archivo descargado
        uses: actions/upload-artifact@v4
        with:
          name: visitas_excel
          path: data/
