name: Descarga Automatizada Diario

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  descargar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

      - name: Instalar dependencias
        run: pip install selenium pytz

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Ver archivos
        run: ls -R data/

      - name: Commit autom√°tico
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"

          git add data/

          if git diff --staged --quiet; then
            echo "Sin cambios"
          else
            git commit -m "Reporte diario $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push
          fi
