name: Descarga Automatizada Diario

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  descargar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar librer√≠as
        run: pip install selenium webdriver-manager pytz
        
      - name: Correr script
        run: python scraper.py
      
      - name: Verificar archivos
        run: ls -R data/
        
      - name: Guardar cambios
        run: |
          git config --global user.name "Bot de Datos"
          git config --global user.email "bot@github.com"
          
          git add data/
          
          if git diff --staged --quiet; then
            echo "No hay cambios para guardar."
          else
            git commit -m "Reporte Diario: $(date +'%Y-%m-%d') [skip ci]"
            git pull --rebase origin main
            git push
          fi
