name: Descarga Automatizada Diario

on:
  schedule:
    - cron: '40 4 * * *'
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  descargar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar librer√≠as
        run: pip install -r requirements.txt
        
      - name: Correr script
        run: python scraper.py
      
      - name: Verificar archivos generados
        run: ls -R
        
      - name: Guardar cambios
        run: |
          git config --global user.name "Bot de Datos"
          git config --global user.email "bot@github.com"
          git add data/
          if git diff --staged --quiet; then
            echo "Sin cambios"
          else
            git commit -m "Datos: $(date +'%Y-%m-%d') [skip ci]"
            git pull --rebase origin main
            git push
          fi
          
      - name: Subir Evidencia Debug
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: evidencia-png
          path: *.png
          retention-days: 5
