name: Descarga visitas diaria

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  descargar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper
        run: python scraper.py
        
      - name: Ver archivos
        run: ls -R data || echo "No se generó carpeta data"

      - name: Subir resultado
        uses: actions/upload-artifact@v4
        with:
          name: reporte-visitas
          path: data/
